### ISSUE TITLE
border-inline-* and border-block-* shorthands have incorrect color computed property

### ISSUE THREAD

**Issue by mahirshah** [mdn/data#101]
In css/properties.json, border-inline and border-block shorthand properties have the incorrect color computed property. For example, the border-inline-start property shows:
```
"border-inline-start": {
    ...
    "computed": [
      "border-width",
      "border-style",
      "color"
    ],
   ...
  }
```
Instead of "border-inline-start-color" as the computed property, it lists "color". Similarly for border-inline-end, border-block-start, and border-block-end.

**Comment by apoorvasingh17** [comment]
Has this issue been resolved?

**Comment by teoli2003** [comment]
Fixed.
