### ISSUE TITLE
Remove spec status from css properties

### ISSUE THREAD

**Issue by teoli2003** [mdn/data#120]
The status (standard/experimental/obsolete) is stored on the browser-compat-data entry. Duplicate information leads to difficulty to maintain coherence, especially when their value set is different.

This can be removed once CSS compat data is fully migrated, and eventual macro using it updated.

**Comment by lahmatiy** [comment]
In case there must be a single source of truth, I believe a status should be stored in `mdn-data` rather than in `browser-compat-data`, because a status is a part of a thing description rather than browser support part. Also, at the moment, looks like `mdn-data` contains more data.

**Comment by teoli2003** [comment]
The list of spec on the standards track is in w3c/browser-spec nowadays. The status of the spec itself is no more relevant. Remnants in mdn/data are irrelevant nowadays. (They should be removed, but that's for another issue).
