### ISSUE TITLE
Remove nonstandard display properties

### ISSUE THREAD

**Issue by mfluehr** [mdn/data#133]
Per https://drafts.csswg.org/css-display/#changes, the `display-inside`, `display-list`, and `display-outside` properties are no longer part of the spec. Moreover, none of them were ever implemented in browsers, so far as I'm aware.

Can we also junk/delete their respective MDN pages?

- [ ] Delete properties from mdn/data.
- [ ] Delete the respective pages on MDN.

**Comment by mfluehr** [comment]
In https://github.com/mdn/data/pull/136, @teoli2003 recommended an "Abandoned proposals" group, or something along those lines. Should I move forward with trying to implement that?

**Comment by Elchi3** [comment]
As said in #136, I'm in favor of deleting the data entries and also the respective MDN pages as this never got any practical meaning.

**Comment by teoli2003** [comment]
Just before removing this, I'm curious to know why they got removed by W3C. @mfluehr can you find a link to the W3C decision?

**Comment by mfluehr** [comment]
I'm not sure this is quite what you want, but here's the best reference I could find: https://lists.w3.org/Archives/Public/www-style/2015May/0134.html

**Comment by teoli2003** [comment]
It took me some time, but I'm convinced that this was correct. Thank you, mfluehr.

**Comment by mfluehr** [comment]
Thanks, @teoli2003. Do you want to remove the respective pages, too?

- https://developer.mozilla.org/en-US/docs/Web/CSS/display-inside
- https://developer.mozilla.org/en-US/docs/Web/CSS/display-list
- https://developer.mozilla.org/en-US/docs/Web/CSS/display-outside

**Comment by teoli2003** [comment]
Done. thx
