### ISSUE TITLE
Add CSS "functions" JSON file

### ISSUE THREAD

**Issue by mfluehr** [mdn/data#135]
Can we add a JSON file for CSS functions, e.g. `linear-gradient()`, `element()`, etc?

Among other things, this would allow us to define the syntax here in this repository, instead of hard-coding it into the MDN reference pages. I think it would also be a step towards allowing functions in the "CSSRef" macro (https://github.com/mdn/kumascript/blob/master/macros/CSSRef.ejs).

**Comment by teoli2003** [comment]
We have to pay attention here: there are functions that can be applies everywhere some types are used (like calc() ), but most are tied to a specific property. 

I wonder if there aren't functions with the same name, tied to different properties, with different behaviours (need to dig to check this one).

The structure of the file may need to take this into account.

**Comment by lahmatiy** [comment]
> I wonder if there aren't functions with the same name, tied to different properties, with different behaviours (need to dig to check this one).

I don't remember such functions. But there are some functions that have different parameters allowed depend on context. For example, see `repeat()` function that used in `<track-repeat>`, `<fixed-repeat>` and `<auto-repeat>` types: https://csstree.github.io/docs/syntax.html#Property:grid-template-columns

**Comment by lahmatiy** [comment]
I checked through dictionaries and found that `minmax()` and `repeat()` have various semantic:

```
minmax( <inflexible-breadth> , <fixed-breadth> )
minmax( <fixed-breadth> , <track-breadth> )
minmax( [ <length> | <percentage> | <flex> | min-content | max-content | auto ] , [ <length> | <percentage> | <flex> | min-content | max-content | auto ] )

repeat( [ <positive-integer> ] , [ <line-names>? <track-size> ]+ <line-names>? )
repeat( [ auto-fill | auto-fit ] , [ <line-names>? <fixed-size> ]+ <line-names>? )
repeat( [ <positive-integer> ] , [ <line-names>? <fixed-size> ]+ <line-names>? )
repeat( [ <positive-integer> | auto-fill ] , <line-names>+ )
repeat( <length-percentage> )
```
I don't think function dictionary is needed, since you can extract function list from syntaxes on demand. I did it recently on https://csstree.github.io/docs/syntax.html (see at the end of sidebar, there are 91 functions – mdn/data + some extensions)

**Comment by teoli2003** [comment]
Agreed. Closing this.
