### ISSUE TITLE
css/properties.json is incomplete

### ISSUE THREAD

**Issue by Kapeli** [mdn/data#149]
Some properties that are missing from css/properties.json:

* justify-items
* justify-self

**Comment by teoli2003** [comment]
Hi! thanks for finding this!

Do you think you could submit a PR for these?

**Comment by Kapeli** [comment]
I tried, but I have no idea what to fill in for the syntax and other fields. Also, the file should be checked for other missing properties as well? Not sure how to do that either.

**Comment by meyer** [comment]
@teoli2003 What’s the best source of truth for what should be in this repository?

https://www.w3.org/TR/css-2017/ ??
https://github.com/w3c/csswg-drafts ??
https://developer.mozilla.org/en-US/docs/Web/CSS/Reference ??

I’d love to contribute. Just not sure where to start.

**Comment by teoli2003** [comment]
Hi!
Things are a little bit more complex, unfortunately. There is no ultimate source of truth existing on the Web.

Properties that are listed here are the ones that has been/are implemented by one browser that shipped. [We can make some exceptions, but that it the idea]

Then for the values of each entry, that is syntax and so, we prime the implementations. If they diverge, we usually follow the spec if it tries to solve the divergence.

CSS 2017 is usually a good start, though I'm not sure about the implementation status (in browsers) of things like CSS Speech, but we will definitively incoroporate additional drafts. The MDN link you gave should use this data/properties.json as a source of truth.

Hope it helps.

**Comment by Kapeli** [comment]
Thank you @pkuczynski! 🙏

**Comment by wbamberg** [comment]
https://github.com/csstree/csstree/issues/81 and https://github.com/mdn/data/pull/184 are still open, but let's get to them soon.

**Comment by pkuczynski** [comment]
@wbamberg shall we close this one?
