### ISSUE TITLE
Parser for the value definition syntax?

### ISSUE THREAD

**Issue by aaronbeall** [mdn/data#153]
The data contains a lot of `syntax` values not expanded into JSON which I guess is in [value definition syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax). Is there a parser for this syntax available, either by MDN or otherwise?

**Comment by lahmatiy** [comment]
You can use [CSSTree](https://github.com/csstree/csstree) to parse syntaxes:

```js
import csstree from 'css-tree';

console.log(csstree.grammar.parse('a || b'))
// { type: 'Group',
//   terms:
//    [ { type: 'Keyword', name: 'a' },
//      { type: 'Keyword', name: 'b' } ],
//   combinator: '||',
//   disallowEmpty: false,
//   multiplier: { comma: false, min: 1, max: 1 },
//   explicit: false }
```

CSSTree also has `grammar.walk()` method to traverse through that AST and `grammar.translate()` method to generate a string from AST. For more examples of usage see https://csstree.github.io/docs/syntax.html source.

**Comment by aaronbeall** [comment]
Thanks that looks like exactly what I was looking for!
