### ISSUE TITLE
Bad value in `data/properties.json` for `border-image-outset`

### ISSUE THREAD

**Issue by tshinnic** [mdn/data#155]
Article [border-image-outset](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-outset)  displays a bad value as the "initial value".   Article [border-image](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image) displays the same bad value as initial value for "border-image-outset".  

The bad value displayed is "0s".  The correct value from ["CSS Backgrounds and Borders Module Level 3"](https://drafts.csswg.org/css-backgrounds-3/#border-image-outset) is "0".  The reference section is [6.4. Edge Overhang: the border-image-outset property](https://drafts.csswg.org/css-backgrounds-3/#the-border-image-outset). 

Both articles use the same macro to generate the displayed block, simply inserting `{{cssinfo}}`.  The problem value can be found at https://github.com/mdn/data/blob/9daccf936f5759ec4acf1147f47f1ffabd642f57/css/properties.json#L1714

The value "0s" is found elsewhere describing 4 properties related to 'delay's or 'duration's, which may be where the mistaken copy-n-paste came from and an explanation for the spurious 's' (for seconds in those other places).

(I'd generate a PR but at the moment I am unable to test the results - it would be a 'blind' untested PR)

**Comment by lahmatiy** [comment]
@tshinnic You're right, initial value is incorrect and should be `0`, as spec says.
Btw, I wrote a [simple script](https://gist.github.com/lahmatiy/db6bd9cd11268bc7c83f0b8b6ceb6269) using CSSTree to check initial values of mdn/data `property.json` and it confirmed the problem (besides others).
