### ISSUE TITLE
Add schema files for validation purposes

### ISSUE THREAD

**Issue by a2sheppy** [mdn/data#19]
As part of our testing and validation before committing changes to the data, we should be using a tool such as [ajv](https://www.npmjs.com/package/ajv) to not only validate that our JSON is structurally sound, but that it matches the schemas for each of the databases we have here.

This would go a long way toward helping to ensure that our data is properly formatted and will reduce the back-and-forth during the PR process.

**Comment by Elchi3** [comment]
Should we work on JSON schemas for our CSS data to make sure our data is coherent before we publish to npm soon?

**Comment by a2sheppy** [comment]
IMHO, yes. I think that’s important to do.

Eric Shepherd
Senior Technical Writer
Mozilla
https://developer.mozilla.org/ <https://developer.mozilla.org/>
Blog: http://www.bitstampede.com/ <http://www.bitstampede.com/>
Twitter: http://twitter.com/sheppy <http://twitter.com/sheppy>

**Comment by lahmatiy** [comment]
I've implemented initial schema validation, see #71.
Feedback is welcomed.
