### ISSUE TITLE
Question regarding the license and usage of data

### ISSUE THREAD

**Issue by octref** [mdn/data#210]
Following up #199, I have made a PR that uses `mdn/data` to enhance the data we have at [vscode-css-languageservice](https://github.com/Microsoft/vscode-css-languageservice): https://github.com/Microsoft/vscode-css-languageservice/pull/91/files. It imports JSON files from `mdn/data` and build a `browser.ts` on top of it.

Then @chriseppstein raised a good question. Does transformation of the original data count as modification?

Q11 of [MPL FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) states if I have any modification I must license the modification in MPL too. And from 1.4 and 1.10 of [MPL](https://www.mozilla.org/en-US/MPL/2.0/), our case could be argued to be "modification" under this clause:

> any file in Source Code Form that results from an addition to, deletion from, or modification of the contents of Covered Software; or

In this case, I think the JSON files here could be considered as "contents of Covered Software", and our use could be considered "modifications". Having part of our codebase in a copyleft license could make people uneasy to adopt it.

@wbamberg Could you consider re-license the data in MIT license or correct my understanding of the license?

**Comment by frenic** [comment]
> Could you consider re-license the data in MIT license or correct my understanding of the license?

I wonder the same thing for [csstype](https://github.com/frenic/csstype).

**Comment by wbamberg** [comment]
@octref , @frenic : I'm not qualified to answer these questions, but I've passed them on to someone who is.

**Comment by chrisdavidmills** [comment]
Sorry for the delay on this. I'm working on an answer at the moment.

I'd like to clarify with you what you are actually doing with our data. From looking at the PR linked above, it looks like you are:

1. Importing the relevant data from our NPM package.
2. Using a program to modify it in some way.
3. Storing it in some kind of package inside your repo?

Is this correct?

It doesn't look like you are storing any of our raw JSON files anywhere inside your codebase. But you are actually storing some of our data somewhere?

With MPL being a file-based license, these are the details that make the difference.

**Comment by octref** [comment]
> Storing it in some kind of package inside your repo?

> It doesn't look like you are storing any of our raw JSON files anywhere inside your codebase. But you are actually storing some of our data somewhere?

We store the transformed data in here: https://github.com/Microsoft/vscode-css-languageservice/blob/master/src/data/browsers.ts.

It's generated by [this script](https://github.com/Microsoft/vscode-css-languageservice/blob/master/build/mdn-data-importer.js) by combining
- [our data](https://github.com/Microsoft/vscode-css-languageservice/blob/master/build/css-schema.xml)
- [mdn data](https://github.com/Microsoft/vscode-css-languageservice/blob/master/build/mdn-data-importer.js#L18-L19)

I also hand-picked documentations for certain css properties from MDN website, and put them in here: https://github.com/Microsoft/vscode-css-languageservice/blob/master/build/mdn-documentation.js

I believe I have attributed the documentation excerpts from MDN properly - There is a disclaimer on this file's license (CC BY-SA 2.5) in the README and a header on that specific file.

**Comment by octref** [comment]
Thanks a lot for the license change! Really appreciate it.
Although it's not required, I'll continue to carry attributions to MDN in here: https://github.com/Microsoft/vscode-css-languageservice.
