### ISSUE TITLE
Is color-adjust standardized?

### ISSUE THREAD

**Issue by octref** [mdn/data#212]
I only found this page: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-print-color-adjust

However the data says:

```
  "color-adjust": {
    "syntax": "economy | exact",
    "media": "visual",
    "inherited": true,
    "animationType": "discrete",
    "percentages": "no",
    "groups": [
      "CSS Color"
    ],
    "initial": "economy",
    "appliesto": "allElements",
    "computed": "asSpecified",
    "order": "perGrammar",
    "status": "standard"
  }
```

Can we have a MDN page for `color-adjust`, if it's standardized?

**Comment by wbamberg** [comment]
It seems like it. We use Bugzilla to track issues in MDN content, requests for docs, etc, so I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1456323 for this.
