### ISSUE TITLE
Include MDN link in data

### ISSUE THREAD

**Issue by wbamberg** [mdn/data#233]
People using mdn/data to embed content in different applications might want to include a link to the docs page for the thing. To enable that we should include a link to the MDN page for the thing.

Note that browser-compat-data already does this via the mdn_url property: https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data.schema.json#L111-L115. I can't see any reason not to do exactly the same thing.

## Acceptance criteria

* For all items in properties.json, selectors.json, atrules.json and types.json, if they have a corresponding MDN page, the item contains a link to the MDN page.

* Schemas and documentation are updated.

**Comment by connorshea** [comment]
This issue and #120 conflict, should we keep browser-compat-data as the source of truth for MDN URLs and spec statuses, or no?

**Comment by wbamberg** [comment]
I'm not sure what this has to do with spec status.

(For https://github.com/mdn/data/issues/120, I actually agree with https://github.com/mdn/data/issues/120#issuecomment-366719673, although this ship might have sailed.)

Just for the MDN URL though, I'm not sure that it has to live in one place or the other. Someone wanting to use the compat data might want to link to MDN, and might not want to drag in another dependency to do so. Someone wanting to use the formal syntax for validation might also want to, and might not want to drag in another dependency.

But I'm open to any solution that meets the requirements of people using the data.

If it were to live only in one place it seems to make more sense for it to live in mdn/data, since mdn/browser-compat-data is more narrowly focused on compat, while mdn/data is more general (unfocused?) "metadata stuff".

**Comment by wbamberg** [comment]
Thanks for your work on this @ddbeck , I think we can call it done.

**Comment by wbamberg** [comment]
I think we should make a minor release for this, bumping the version to 1.2.0. @chrisdavidmills , @Elchi3 , does this sound good to you?

**Comment by Elchi3** [comment]
Yes, a schema addition (but a non-breaking one) should bump the minor version, so 1.2.0 sounds good to me. Great work! :+1:
