### ISSUE TITLE
`place-self` property missing

### ISSUE THREAD

**Issue by connorshea** [mdn/data#253]
This property isn't included in the data repository despite being standard: https://developer.mozilla.org/en-US/docs/Web/CSS/place-self

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/data/pull/304

**Comment by octref** [comment]
Hey @chrisdavidmills, do you mind publishing a new version so I can fix https://github.com/Microsoft/vscode/issues/64835? Thanks in advance.

**Comment by wbamberg** [comment]
@octref , @chrisdavidmills , this should be done now.

**Comment by octref** [comment]
Adopted in latest version. Thanks a lot!

**Comment by chrisdavidmills** [comment]
@wbamberg yay, cheers Will!
