### ISSUE TITLE
Write a script to check summaries against short descriptions guidelines

### ISSUE THREAD

**Issue by wbamberg** [mdn/data#275]
We have guidelines for how summaries should be written to work as short descriptions. In this story we will write a script to check summaries in MDN pages against the guidelines. This will eventually be part of the script to update mdn/data from the Wiki content, and in the meantime it will be helpful in adapting the summaries that are already present in MDN.

`Cf:Low` because @ddbeck is going to be out for much of the next sprint.

## Acceptance criteria

* a script is written, reviewed, and merged into mdn/data
* the script can fetch summaries from MDN pages and validate them against our guidelines

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by chrisdavidmills** [comment]
I think @ddbeck did this? Can we close this issue?

**Comment by wbamberg** [comment]
> I think @ddbeck did this? Can we close this issue?

The PR is filed but needs at least some small style changes before merging: https://github.com/mdn/short-descriptions/pull/4.

**Comment by jmswisher** [comment]
That PR is merged now.
