### ISSUE TITLE
Drop motion in favor of offset

### ISSUE THREAD

**Issue by octref** [mdn/data#314]
From this page https://developer.mozilla.org/en-US/docs/Web/CSS/offset and the spec, `motion` is changed to `offset` in the spec proposal.

Should I remove the `motion` properties, or should I add a deprecated status for them? (I think it makes more sense to remove them, since these properties are dropped in the experimental phase).

**Comment by chrisdavidmills** [comment]
Yeah, I'd just remove them.

**Comment by connorshea** [comment]
I think this was resolved by #349?

**Comment by octref** [comment]
Yes, fixed by #349. Thanks.
