### ISSUE TITLE
`mask-repeat` has incorrect initial value

### ISSUE THREAD

**Issue by alexander-akait** [mdn/data#351]
Spec: https://drafts.fxtf.org/css-masking-1/#the-mask-repeat

Right value: `no-repeat`

**Comment by constgen** [comment]
Right value is `repeat`

**Comment by teoli2003** [comment]
According to the spec, it is `repeat`. As this what is in mdn/data, I'm going to close this. If I'm mistaken, feel free to explain why and I'll reopen the issue.
