### ISSUE TITLE
Shorthand property syntax definitions

### ISSUE THREAD

**Issue by squidfunk** [mdn/data#367]
This is more of a question than an issue: why are some of the shorthand definitions not composed out of their contained properties but the syntaxes of those properties? 

For example, the syntax of `border-left` is defined as:

```
<line-width> || <line-style> || <color>
```

In my opinion it should be:

```
<'border-left-width'> || <'border-left-style'> || <'border-left-color'>
```

This would allow for downstream projects to better reason about longhand/shorthand property definitions. Is this intentional? If not, I could submit some PRs to improve on those definitions.

---

https://github.com/mdn/data/blob/8889434104261d634df67dcd2f0f7db4ef2f59db/css/properties.json#L3039-L3069

**Comment by chrisdavidmills** [comment]
We tend to just go with what the spec says for the formal syntax. In the case of `border-left`, it is stated in the spec here:

https://drafts.csswg.org/css-backgrounds-3/#border-shorthands

I see what you are saying; your syntax makes more logical sense from the point of view of the average web dev. But there is probably a reason this is like it is, and formal syntax is not really for use of average web devs.

I'd advise you not to do this, as I think it would be a waste of your time. We don't currently have a plan for what we want to do about formal syntax; we've even discussed removing it from our pages, as so few peopple actually use it. But this is a decision we'll have return to when we have more time,

**Comment by squidfunk** [comment]
Thanks for the quick response! I find this repository to be super awesome because it condenses so much information about CSS syntax in an easily consumable way that can be used in many different ways to improve developer experience and tooling down the line. Please keep the syntax definitions!

Your approach of keeping as close as possible to the spec is definitely the best approach and I apologize for not looking it up before opening this issue – it should really be opened on the csswg-drafts repository.

Please don't remove it!

**Comment by chrisdavidmills** [comment]
We won't remove them lightly, don't worry. I appreciate the feedback.

**Comment by squidfunk** [comment]
As a side note, this is one of the reasons why this data is awesome:

![css-data-types-dependency-graph](https://user-images.githubusercontent.com/932156/58509810-b9dfaf80-8197-11e9-8fe3-a40019b45acc.png)
