### ISSUE TITLE
repeat() syntax not found in DB

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/data#394]
This could be related to #135.

When opening [MDN docs on repeat()](https://developer.mozilla.org/de/docs/Web/CSS/repeat), the wiki tells me, that „Syntax not found in DB!” for the Formal Syntax.

I would expect either to find a link to add that syntax - or the block hidden.
Right now I feel like MDN is shouting at me :-(

**Comment by chrisdavidmills** [comment]
I've deleted the Formal syntax section on the English page; the syntax section above it seems to cover the formal syntax pretty well.

We need a proper solution to this, and no-one has time to work on this right now. I'll file a note about it to our planning so we don't forget about it.
