### ISSUE TITLE
Remove HTML entities from syntaxes

### ISSUE THREAD

**Issue by lahmatiy** [mdn/data#40]
For historical reasons syntaxes contain HTML entities as a replacement for symbols like `<`, `>` or `&`. It makes hard to read, maintain and use it in non-HTML contexts.

Suggestion is replace HTML entities to corresponding symbols.

(based on #8)

**Comment by SebastianZ** [comment]
I'm definitely for this, as it would make the syntaxes much more readable (and even save some characters).

I just want to note that we will then need to find a solution for formatting we currently use (i.e. `<var>` [used to indicate variables like in `minmax( <var>min</var>, <var>max</var> )`] and `\n` [used for line breaks like in `&lt;feature-type&gt; {\n  &lt;feature-value-declaration-list&gt;\n}`).

Sebastian

**Comment by lahmatiy** [comment]
There are 4 cases with `<var>`:
- `an-plus-b` syntax in `syntax.json` - `An+B` is realy complex and defined aside in spec. It's a generic type and should be defined in `types.json`. And `an-plus-b` syntax in `syntax.json` should be replaced for another syntax `<an-plus-b> | odd | even`
- `minmax` syntax in `syntax.json` - it's wrong syntax actually, two solutions here:
  - replace `min` and `max` for reference to syntax `<length> | <percentage> | <flex> | min-content | max-content | auto` - definition become `minmax( <new-syntax-name>, <new-syntax-name> )`
  - define new syntaxes `min` and `max` - definition become `minmax( <min>, <max> )`
- In description of pseudo syntax in `selectors.json`. It's quite strange why for pseudo is using complete rule syntax, e.g.
```
  ":active": {
    "syntax": ":active { <var>style properties</var> }",
    "groups": [
      "Pseudo-classes"
    ],
    "status": "standard"
  },
```
I think `{ <var>style properties</var> }` is odd and should be removed.
- `:any-link` syntax in `selectors.json`. Currently syntax is `:any-link( <var>style properties</var> )`. It's a mistake, since `:any-link` is not a functional pseudo (and here means ` { <var>style properties</var> }` I guess).
