### ISSUE TITLE
Extend format of css/syntaxes.json to contain additional details

### ISSUE THREAD

**Issue by lahmatiy** [mdn/data#41]
`css/syntaxes.json` is single file storing a string as value. It prevents us to add more details about syntax, e.g. Spec it defined or what it used for.

> Any additional information can be useful. Sometimes is too hard to find details about property or syntax - and no clue what it uses for.

Suggestion is extend file format to contain not only syntax but additional details too.

(based on #8)

**Comment by SebastianZ** [comment]
I generally like this suggestion. It makes the JSON structure consistent to the one of the other files and allows to add additional information.

Having said that, it still needs to be discussed which information should be added.

In my [comment to issue #8](https://github.com/mdn/data/issues/8#issuecomment-255801851) I've mentioned that spec. information is currently still maintained in the {{SpecName}} and {{spec2}} macros (which where [meanwhile moved to GitHub](https://github.com/mozilla/kumascript/blob/master/macros/)).
Their "tags" could be reused for this to indicate a reference, e.g. in the `"groups"` array or a new property.

Sebastian

**Comment by lahmatiy** [comment]
We can start with simple convertation and add additional fields later
```
"name": "<syntax>"
->
"name": {
  "syntax": "<syntax>"
}
```
