### ISSUE TITLE
`-moz-force-broken-image-icon` value should use bracket range notation

### ISSUE THREAD

**Issue by pyoor** [mdn/data#429]
According to https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-force-broken-image-icon, the `-moz-force-broken-image-icon` only supports a value of 0 or 1.  As such, the value definition should be changed to:

`<number [0,1]>`

Current definition:
https://github.com/mdn/data/blob/537dde75199d5d8c1904c5e9e12680e7af45afd2/css/properties.json#L921

**Comment by chrisdavidmills** [comment]
Thanks for reporting! Would you be able to submit a PR to fix this?
