### ISSUE TITLE
Invalid syntax for CSS ray() function

### ISSUE THREAD

**Issue by pyoor** [mdn/data#433]
The CSS ray() is defined as follows (via https://drafts.fxtf.org/motion-1/#valdef-offset-path-ray):
`ray( [ <angle> && <size> && contain? ] )`

The current definition marks `<size>` as optional:
https://github.com/mdn/data/blob/e49d197ab3e7fd8b8036e6e7ad46a5aeb1f1a09b/css/properties.json#L6619

This line should be changed to:
`"syntax": "none | ray( [ <angle> && <size> && contain? ] ) | <path()> | <url> | [ <basic-shape> || <geometry-box> ]", `

**Comment by chrisdavidmills** [comment]
Thanks for the report, @pyoor . Would you be willing to make a quick PR to fix this?
