### ISSUE TITLE
[feature] It's awesome if i can add api to my watch list like wiki

### ISSUE THREAD

**Issue by ishowman** [mdn/data#487]
I wish to get notify if content of api changes.
It's awesome to support watch like wiki.

**Comment by sigveio** [comment]
Hey @ishowman! Do you mean to get notified when the JSON is updated?

At the moment, I think the only way to reliably do this is to create a script to fetch the files and compare to a local version / snapshot.

Alternatively, I suppose you could use GitHub's notification feature set to follow pull requests:

![Screenshot 2021-07-28 at 18 32 17](https://user-images.githubusercontent.com/6737410/127361556-18e05eab-3121-4185-98ec-8e6b1d1fac3c.png)
(You can find it up in the right corner of the page.)

This should notify you when changes are being suggested. =)

**Comment by bsmth** [comment]
Closing as I think the question is answered above!
