### ISSUE TITLE
Initial value of `color`

### ISSUE THREAD

**Issue by sigveio** [mdn/data#495]
Combing through drafts from the CSS Working Group I noticed that as of [~january last year](https://github.com/w3c/csswg-drafts/issues/4608) it was decided that the `initial` value of `color` would use `CanvasText`. This was merged in w3c/csswg-drafts/pull/4714 and has been published in the last two versions of the working draft for [CSS Color Module Level 4](https://www.w3.org/TR/css-color-4/#the-color-property) (css-color-4).

I tried to trace the status with the major browser platforms, and I can see mozilla/gecko and chronium appears to have fixed [[mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1590894), [chronium](https://bugs.chromium.org/p/chromium/issues/detail?id=1015968)] and shipped [[mozilla](https://hg.mozilla.org/mozilla-central/rev/3f2a791d050a), [chronium](https://chromium-review.googlesource.com/c/chromium/src/+/1864378)]. There doesn't appear to be any public signals from WebKit, but judging from the [web-platform-tests](https://wpt.fyi/results/css/css-color/color-initial-canvastext.html?label=master&label=stable&aligned) it looks good there too.

I'm thinking that it could be time to update the `initial` value of `color` in the MDN CSS property data to `CanvasText` instead of the special keyword "variesFromBrowserToBrowser". As it's no longer flagged as "depends on user agent" in css-color-4.

Besides keeping the [MDN developer documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/color#formal_definition) for `color` (which already [references css-color-4](https://developer.mozilla.org/en-US/docs/Web/CSS/color#specifications)) up-to-date, it would also be useful for build tools that rely on the data to optimise or minimise CSS.

But I thought I would ask for feedback to see if there are arguments against this change before I submit a PR. =)

Also; for future reference - since I wouldn't mind to continue helping you keep the data up-to-date - are there any official criteria or common practices for MDN data in terms of determining when it's deemed safe to update a property? Am I correct in thinking that you generally follow the current working draft and accepted browser support/implementation? Perhaps you could shed some light on that, @rachelandrew?

**Comment by rachelandrew** [comment]
I think the data should be correct as to the current spec, if user agents are doing something different the best place for that is in BCD. If you could also update BCD in that case (or at least raise an issue) that will help the actual state of things to also be demonstrated.

**Comment by sigveio** [comment]
Roger that - thanks for the swift follow up :relieved:  

User agent behaviour in recent versions seems consistent across the board, but I will see if I can map how far back this goes (+check mobile versions) and follow up in BCD too. That's a good point! 👍
