### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by ben-eb** [mdn/data#5]
In the spirit of other large datasets, such as [caniuse](https://www.npmjs.com/package/caniuse-db), it would be really great to publish this data to npm as well. By doing so it would mean versioning the data so that any breaking changes could be handled in a developer's own time, rather than relying on the latest `master` branch from GitHub.

**Comment by lahmatiy** [comment]
@Elchi3 @SebastianZ Is there any plans to publish on npm?

**Comment by SebastianZ** [comment]
I didn't have time yet to read into how to publish the data as npm package, but I think that's something that one of the MDN staff should do. (I'm just a volunteer.)

Sebastian

**Comment by lahmatiy** [comment]
>  I think that's something that one of the MDN staff should do

Agree. That's why nobody else did this yet. We need to attract their attention to this issue.
Publishing is quite simple. A `package.json` file should be added and then `npm publish`.

**Comment by Elchi3** [comment]
I will bring it up in the team and get us an account there etc.

**Comment by Elchi3** [comment]
Update: I got us an account https://www.npmjs.com/~mdn

**Comment by iamstarkov** [comment]
@Elchi3 can you publish it?

**Comment by Elchi3** [comment]
@iamstarkov I would like to soonish. There is PR #36 that adds the package file, but it is pending review.
Also, I would like to work on issue #19 and issue #40 before publishing.

**Comment by lahmatiy** [comment]
@Elchi3 I think #19 is not a blocker. I can fix #40 (I did this before) and also check syntax is correct by `csstree` lexer.

**Comment by Elchi3** [comment]
@iamstarkov helped with merging #36. (thank you!) 

The next steps he suggests:
- add CHANGELOG for initial relase
- go with minor release: $ npm version minor && npm publish (minor because #40 is kind of breaking change, so you dont want to have 2.0.0 as a second release)

Sounds good to everyone?

**Comment by lahmatiy** [comment]
I would like to fix #40 and #41 (it's also breaking change) before initial release. I may to make PRs for these issues today.

One more possible option is using `-alpha`/`-prerelease` postfix for version.

**Comment by lahmatiy** [comment]
@Elchi3 Please, review PR #52. It's a blocker for upcoming changes.

I tested new files (`properties.json` and `syntaxes.json`) with csstree, looks nothing is broken. Btw I found one missed property [`offset-position`](https://csstree.github.io/docs/syntax.html#properties:offset) ;)

**Comment by lahmatiy** [comment]
@Elchi3 Please, review PR #66. That's the last breaking change we need to do before publish or is there something else that's blocking publishing?

**Comment by Elchi3** [comment]
I'd like to merge #81 and #66 and then publish. Any other thoughts? Should it be 1.0.0?

**Comment by lahmatiy** [comment]
It would be nice to fix #63 before publish. It has a few edge cases and requires a resolution for #61. But it may be postponed for future releases.

I don't see a reason for a version rather than 1.0.

**Comment by Elchi3** [comment]
I think #61 requires a significant amount of work (on this repo and on MDN), so if we make that block the publishing, it will take another while until there will be a package available. My feeling here was that people are already waiting for the npm package. On MDN we would certainly like to load this from npm sooner than later.

I have no strong feeling either way. Maybe others have opinions on what they prefer.

**Comment by lahmatiy** [comment]
Agree. We can improve indefinitely. I'm voting for publishing in current state.

**Comment by ben-eb** [comment]
I'm happy with publishing the data in its current state too, so long as breaking changes such as #61 are handled by semver major increments. 😄

**Comment by Elchi3** [comment]
Yes, we should use semver major increments in these cases. Right now we are just breaking things with no notice, so I think it will be better to publish and indicate breakage this way as well.

**Comment by Elchi3** [comment]
https://www.npmjs.com/package/mdn-data :tada:
