### ISSUE TITLE
Fix rendering of ranged data types

### ISSUE THREAD

**Issue by pyoor** [mdn/data#504]
I recently noticed that https://github.com/mdn/data/pull/503 was merged to address an issue in the rendering of ranged data types.  This is not the first time this has come up.  See https://github.com/mdn/data/pull/448

The correct approach here is not to modify the data type as ranged values are part of the CSS Values and Units specification and have been since [css-values-3](
https://drafts.csswg.org/css-values-3/#numeric-ranges).

I would be interested in looking at this issue if someone can direct me to the code responsible for rendering the data types.

**Comment by wbamberg** [comment]
I believe this works correctly now? https://developer.mozilla.org/en-US/docs/Web/CSS/border-top-width#formal_syntax

**Comment by teoli2003** [comment]
Yes, the new CSSSyntax macro fixes this.
