### ISSUE TITLE
Appearance initial value is "none", not "auto"

### ISSUE THREAD

**Issue by kof** [mdn/data#554]
Hi, 
it seems data for appearance is wrong, both firefox and chrome have implemented initial as none and w3c specified none

https://www.w3.org/TR/2021/WD-css-ui-4-20210316/#propdef-appearance

**Comment by teoli2003** [comment]
Yes, this is correct: the proposed initial value was `auto` but was later changed (and implemented) to `none` for compatibility purposes.

Background information: [CSSWG](https://github.com/w3c/csswg-drafts/issues/1250) and [Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1333482)

I'll create a PR shortly to fix this.
