### ISSUE TITLE
Property background-position-x and -y not quite correct

### ISSUE THREAD

**Issue by kof** [mdn/data#555]
w3c and both firefox and chrome show 0% for both background-position-x and background-position-y

While technically left and top is also correct, I think we should stick with the spec (yeah I found it because the logic I am writing requires an exact match with the browser value)

https://drafts.csswg.org/css-backgrounds/#propdef-background-position

**Comment by teoli2003** [comment]
I agree, and it makes these values coherent with the initial value of `background-position` that is `0% 0%`.

PR incoming.
