### ISSUE TITLE
Not sure if background-size initial "auto auto" is correct

### ISSUE THREAD

**Issue by kof** [mdn/data#556]
Chrome and firefox show "auto" as a single value, w3c too
https://drafts.csswg.org/css-backgrounds/#the-background-size

**Comment by teoli2003** [comment]
That's technically correct, but the spec also says:

> The first value gives the width of the corresponding image, the second value its height. If only one value is given the second is assumed to be [auto](https://www.w3.org/TR/css-backgrounds-3/#valdef-background-size-auto).

So `auto` is a kind of shorthand for `auto auto`. 

I think it may be clearer to list both values.  (Feel free to reopen if you have more arguments).
