### ISSUE TITLE
Issue with "outline-style": Formal Syntax incorrectly implies that all border-style values can be used.

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/data#567]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/outline-style

#### What information was incorrect, unhelpful, or incomplete?
Formal syntax
auto | &lt;'border-style'&gt;

#### What did you expect to see?
Formal syntax
auto | &lt;outline-line-style&gt;

According to [specification](https://w3.org/TR/css-ui-4/#typedef-outline-line-style) outline-style property doesn't accept value "hidden", while border-style does. I believe it will be better to change Formal Syntax and mention how outline-line-style is different from border-style.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/outline-style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/outline-style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/outline-style/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by yarusome** [comment]
@teoli2003 Since the transition of `{{CSSSyntax}}` to webref, I guess this issue can now be closed (as well as the PR).

**Comment by teoli2003** [comment]
There are third-party users of mdn/data.
