### ISSUE TITLE
Normalize media field values in css/properties.json

### ISSUE THREAD

**Issue by lahmatiy** [mdn/data#63]
`media` field contains strings only, but those strings have various meanings:
- media name
- comma separated list of media names
- special value (`none`, `noPracticalMedia`, `visualInContinuousMediaNoEffectInOverflowColumns`)

I'm suggesting to normalize values:
- left media name strings as is or convert it to single item array
- convert comma separated lists to arrays
- apply to special values solution from #61

**Comment by Elchi3** [comment]
This applies to css/at-rules.json (descriptors) as well. Just saw `"media": "visual, continuous"` and I also think it would be better to have `"media": ["visual", "continuous"]`.

**Comment by lahmatiy** [comment]
@Elchi3 That's great! I'll send a PR then.
