### ISSUE TITLE
Split and merge `syntaxes.json` into `functions.json` and `types.json`

### ISSUE THREAD

**Issue by yarusome** [mdn/data#670]
### What information was incorrect, unhelpful, or incomplete?

[`syntaxes.json`](https://github.com/mdn/data/blob/main/css/syntaxes.json) contains data for both CSS functional notations and CSS types, but there already exist [`functions.json`](https://github.com/mdn/data/blob/main/css/functions.json) and [`types.json`](https://github.com/mdn/data/blob/main/css/types.json) for such data.

I'm working on a script for diffing mdn/data and w3c/webref, and the existence of `syntaxes.json` would make the script less useful since this file increases the complexity of comparison bewteen the two data sources.

### What did you expect to see?

This file be split and merged into `functions.json` and `types.json`.

Incidentally, [`functions.md`](https://github.com/mdn/data/blob/main/css/functions.md) is not at all explaining the structure of `functions.json`, so it should be corrected as well.

### Do you have anything more you want to share?

I'll make a PR if this reorganization is agreed but no one does it, but that would be after I having finished writing and testing the script (probably in June).

**Comment by lahmatiy** [comment]
I missed when `functions.json` was added. As to me it should be merged back into `syntaxes.json`. The `types.json` is actually contains generic types, in other words types that has no syntax definition but a prose definition in CSS specs. Having a split in functions and other types makes no sense in terms of CSS.

**Comment by yarusome** [comment]
I found that `types.json` contain both prose-only types (such as [`<number>`](https://drafts.csswg.org/css-values/#numbers)) and types that do have syntaxes (such as [`<display-internal>`](https://drafts.csswg.org/css-display/#typedef-display-internal)), meanwhile the [schema](https://github.com/mdn/data/blob/main/css/types.md) for `types.json` doesn't allow for a `syntax` key. I could add a special case to split types into `syntaxes.json` and `types.json` based on the presence/absence of `syntax`, but this dichotomy seems unnecessary :thinking: (I'll leave `units.json` as it is despite of the fact that their types are "value" in Webref).

So there're two ways to move forward:

  1. Split any data in Webref of the "type" type into `syntaxes.json` and `types.json` based on the presence/absence of `syntax`.
  2. Change the schema for `types.json`, and split `syntaxes.json` into `funtions.json` and `types.json`.

**Comment by caugner** [comment]
@yarusome Can you please take a look at [my previous comment](https://github.com/mdn/data/issues/670#issuecomment-1739747890)?

**Comment by caugner** [comment]
Closing as stale.
