### ISSUE TITLE
All counter-style keywords not listed

### ISSUE THREAD

**Issue by kof** [mdn/data#679]
### What information was incorrect, unhelpful, or incomplete?

When you look at list-style-type  https://github.com/mdn/data/blob/a1d5d41b59a0bbc5931038e8bbd73c63007e5cac/css/properties.json#L6341-L6342 it references  `<counter-style>` and yet I found nowhere "counter-style" keywords  referenced on mdn https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

"space-counter", "disc", "circle" etc

### What did you expect to see?

I would expect that https://github.com/mdn/data/blob/main/css/syntaxes.json#L200 lists those keywords

**Comment by kof** [comment]
@caugner but where do you see that leading to the definitions of "space-counter", "disc", "circle"?

**Comment by OnkarRuikar** [comment]
> @caugner but where do you see that leading to the definitions of "space-counter", "disc", "circle"?

The value "space-counter" used on the page is [a custom counter](https://github.com/mdn/interactive-examples/blob/88def0613143386b6214a6b20d429d7d66ce1e43/live-examples/css-examples/lists/list-style.css#L30) that we've defined for the demo.

If you are talking about the [Formal Syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type#formal_syntax) section on the MDN page then it is now rendered using [`@webref/css`](https://www.npmjs.com/package/@webref/css) package. Webref automatically extracts definitions from specs. We are [working on updating the MDN platform code](https://github.com/mdn/yari/pull/9743) to get the latest syntax.
