### ISSUE TITLE
[meta] Add info about `release-please` requirements in PR template

### ISSUE THREAD

**Issue by bsmth** [mdn/data#687]
We should document how to ensure changes are included in changelog and trigger a release

CCing @caugner

**Comment by bsmth** [comment]
Fixed in:

- [x] https://github.com/mdn/data/pull/668
- [x] https://github.com/mdn/data/pull/689

**Comment by OnkarRuikar** [comment]
A GitHub workflow failing if PR title doesn't start with `fix`, `chore `, or `feat` would be nice.
