### ISSUE TITLE
Missing CSS properties defined in SVG

### ISSUE THREAD

**Issue by bsmth** [mdn/data#750]
This is a tracker issue so we don't forget to add the data for these props.

- [x] https://github.com/mdn/content/pull/35228 `shape-rendering`
- [x] https://github.com/mdn/content/pull/35170 `stop-opacity`, `stop-color`
- [x] https://github.com/mdn/content/pull/35107 `marker-start`, `marker-mid`, `marker-end`
- [x] https://github.com/mdn/content/pull/35167 `text-anchor`
- [x] https://github.com/mdn/content/pull/34931 `x` and `y`
- [x] https://github.com/mdn/content/pull/35259 `stroke`

__Related issues:__

- [x] https://github.com/mdn/content/issues/34763

**Comment by estelle** [comment]
SVG CSS attributes:

- [ ] [`clip-rule`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-rule)
- [ ] [`color-interpolation-filters`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-interpolation-filters) (Redirects to SVG)
- [ ] [`cx`](https://developer.mozilla.org/en-US/docs/Web/CSS/cx)
- [ ] [`cy`](https://developer.mozilla.org/en-US/docs/Web/CSS/cy)
- [ ] [`dominant-baseline`](https://developer.mozilla.org/en-US/docs/Web/CSS/dominant-baseline) (Redirects to SVG)
- [ ] [`fill`](https://developer.mozilla.org/en-US/docs/Web/CSS/fill) (Redirects to SVG)
- [ ] [`fill-opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/fill-opacity) (Redirects to SVG)
- [ ] [`fill-rule`](https://developer.mozilla.org/en-US/docs/Web/CSS/fill-rule) (Redirects to SVG)
- [ ] [`marker`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker) 
- [ ] [`marker-end`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-end) (Redirects to SVG)
- [ ] [`marker-mid`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-mid) (Redirects to SVG)
- [ ] [`marker-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-start) (Redirects to SVG)
- [ ] [`r`](https://developer.mozilla.org/en-US/docs/Web/CSS/r)
- [ ] [`rx`](https://developer.mozilla.org/en-US/docs/Web/CSS/rx)
- [ ] [`ry`](https://developer.mozilla.org/en-US/docs/Web/CSS/ry)
- [ ] [`shape-rendering`](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-rendering) (Redirects to SVG)
- [ ] [`stop-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/stop-color) (Redirects to SVG)
- [ ] [`stop-opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/stop-opacity) (Redirects to SVG)
- [ ] [`stroke`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke) (Redirects to SVG)
- [ ] [`stroke-dasharray`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-dasharray) (Redirects to SVG)
- [ ] [`stroke-dashoffset`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-dashoffset) (Redirects to SVG)
- [ ] [`stroke-linecap`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-linecap) (Redirects to SVG)
- [ ] [`stroke-linejoin`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-linejoin) (Redirects to SVG)
- [ ] [`stroke-miterlimit`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-miterlimit) (Redirects to SVG)
- [ ] [`stroke-opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-opacity) (Redirects to SVG)
- [ ] [`stroke-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-width) (Redirects to SVG)
- [ ] [`text-anchor`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-anchor) (Redirects to SVG)
- [ ] [`vector-effect`](https://developer.mozilla.org/en-US/docs/Web/CSS/vector-effect)
- [ ] [`word-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap) (Redirects to overflow-wrap)
- [ ] [`x`](https://developer.mozilla.org/en-US/docs/Web/CSS/x)
- [ ] [`y`](https://developer.mozilla.org/en-US/docs/Web/CSS/y)

**Comment by skyclouds2001** [comment]
copied full list

- [ ]  [clip-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-rule)
- [ ]  [color-interpolation-filters](https://developer.mozilla.org/en-US/docs/Web/CSS/color-interpolation-filters)
- [ ]  [cx](https://developer.mozilla.org/en-US/docs/Web/CSS/cx)
- [ ]  [cy](https://developer.mozilla.org/en-US/docs/Web/CSS/cy)
- [ ]  [dominant-baseline](https://developer.mozilla.org/en-US/docs/Web/CSS/dominant-baseline)
- [ ]  [fill](https://developer.mozilla.org/en-US/docs/Web/CSS/fill)
- [ ]  [fill-opacity](https://developer.mozilla.org/en-US/docs/Web/CSS/fill-opacity)
- [ ]  [fill-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/fill-rule)
- [ ]  [marker](https://developer.mozilla.org/en-US/docs/Web/CSS/marker)
- [ ]  [marker-end](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-end)
- [ ]  [marker-mid](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-mid)
- [ ]  [marker-start](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-start)
- [ ]  [r](https://developer.mozilla.org/en-US/docs/Web/CSS/r)
- [ ]  [rx](https://developer.mozilla.org/en-US/docs/Web/CSS/rx)
- [ ]  [ry](https://developer.mozilla.org/en-US/docs/Web/CSS/ry)
- [ ]  [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-rendering)
- [ ]  [stop-color](https://developer.mozilla.org/en-US/docs/Web/CSS/stop-color)
- [ ]  [stop-opacity](https://developer.mozilla.org/en-US/docs/Web/CSS/stop-opacity)
- [ ]  [stroke](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke)
- [ ]  [stroke-dasharray](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-dasharray)
- [ ]  [stroke-dashoffset](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-dashoffset)
- [ ]  [stroke-linecap](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-linecap)
- [ ]  [stroke-linejoin](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-linejoin)
- [ ]  [stroke-miterlimit](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-miterlimit)
- [ ]  [stroke-opacity](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-opacity)
- [ ]  [stroke-width](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-width)
- [ ]  [text-anchor](https://developer.mozilla.org/en-US/docs/Web/CSS/text-anchor)
- [ ]  [vector-effect](https://developer.mozilla.org/en-US/docs/Web/CSS/vector-effect)
- [ ]  [word-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap)
- [ ]  [x](https://developer.mozilla.org/en-US/docs/Web/CSS/x)
- [ ]  [y](https://developer.mozilla.org/en-US/docs/Web/CSS/y)

**Comment by skyclouds2001** [comment]
so stop-color & stop-opacity are the last ones and can be closed by https://github.com/mdn/data/pull/782

**Comment by estelle** [comment]
we are missing `lighting-color`, `flood-color`, and `flood-opacity`

**Comment by skyclouds2001** [comment]
yes, they alson listed in https://jc-verse.github.io/mdn-graph/warnings

**Comment by skyclouds2001** [comment]
rest in https://github.com/mdn/data/pull/787

**Comment by skyclouds2001** [comment]
see https://github.com/mdn/data/issues/59
