### ISSUE TITLE
Question: Is there any api or way i can pull in some of the data json files?

### ISSUE THREAD

**Issue by matt3224** [mdn/data#97]
Hi,

I would like to work on a small idea i have for a electron react app that pulls in a list of css color names and displays them. I see theres a data/css/syntaxes.json file here, and wondered if this data was accessible via a rest api somewhere?

Thanks,

**Comment by jwhitlock** [comment]
We're currently distributing this as an npm package, which can be installed with ``npm install mdn/data``. I don't think we have any example code for using it yet, but we're modelling it on our npm package for https://github.com/mdn/browser-compat-data, used in the KumaScript macro [compat](https://github.com/mozilla/kumascript/blob/master/macros/Compat.ejs).  That may give you an idea for bundling the data in your own app, or building an API on top of it.

**Comment by Elchi3** [comment]
A REST API is currently not planned as part of this project, but as @jwhitlock mentions, you can load it as an npm package and have access to the data that way.
